# Generated by Django 4.0.6 on 2022-08-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueluser',
            name='duels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.duels'),
        ),
    ]
