# Generated by Django 4.0.6 on 2022-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duels',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.dueluser'),
        ),
    ]
