# Generated by Django 4.0.6 on 2022-08-06 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_armies_duel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duel',
            new_name='Duels',
        ),
    ]
