# Generated by Django 4.0.6 on 2022-08-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_duel_duels'),
    ]

    operations = [
        migrations.AddField(
            model_name='duels',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tournaments'),
        ),
    ]
