# Generated by Django 4.0.6 on 2022-08-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_duels_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duels',
            old_name='hp1',
            new_name='hp_enemy',
        ),
        migrations.RenameField(
            model_name='duels',
            old_name='hp2',
            new_name='hp_our',
        ),
    ]
