# Generated by Django 4.0.6 on 2022-08-06 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_rename_hp_enemy_duels_enemy_rename_hp_our_duels_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duels',
            name='enemy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='duels',
            name='user',
        ),
        migrations.AddField(
            model_name='duels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
