# Generated by Django 4.0.6 on 2022-08-06 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_alter_duels_enemy_remove_duels_user_duels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duels',
            name='army',
        ),
        migrations.AddField(
            model_name='duels',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.armies'),
        ),
        migrations.AlterField(
            model_name='duels',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tournaments'),
        ),
        migrations.AlterField(
            model_name='duels',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
