# Generated by Django 4.0.6 on 2022-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_duels_army'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duels',
            name='enemy',
        ),
        migrations.AddField(
            model_name='duels',
            name='enemy_army',
            field=models.CharField(choices=[], default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duels',
            name='enemy_hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duels',
            name='enemy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
