# Generated by Django 4.0.6 on 2022-09-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-data_updated', '-data_create']},
        ),
    ]
