# Generated by Django 4.0.6 on 2022-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descrition',
            new_name='description',
        ),
    ]
