# Generated by Django 4.0.6 on 2022-09-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_duels_winner_alter_tournaments_name'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.CharField(default=2143, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='tournament',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tournaments'),
        ),
    ]
